ifdef CONFIG_ARCH_HOST
arch := arch/host
include arch/host/Makefile
endif

ifdef CONFIG_ARCH_ARM
arch := arch/arm
include arch/arm/Makefile
endif

ifdef CONFIG_ARCH_EZ80
arch := arch/ez80
include arch/ez80/Makefile
endif
